import type * as backendApi from "../../../backend/src/services/api.functions";
import { createClientFn } from "./api-client";

export const listMyOrganizations = createClientFn("listMyOrganizations", "GET") as typeof backendApi.listMyOrganizations;
export const createOrganization = createClientFn("createOrganization", "POST") as typeof backendApi.createOrganization;
export const bootstrapOrganization = createClientFn("bootstrapOrganization", "POST") as typeof backendApi.bootstrapOrganization;
export const getDashboardStats = createClientFn("getDashboardStats", "GET") as typeof backendApi.getDashboardStats;
export const listRecentActivity = createClientFn("listRecentActivity", "GET") as typeof backendApi.listRecentActivity;
export const listProjects = createClientFn("listProjects", "GET") as typeof backendApi.listProjects;
export const createProject = createClientFn("createProject", "POST") as typeof backendApi.createProject;
export const listWorkspaces = createClientFn("listWorkspaces", "GET") as typeof backendApi.listWorkspaces;
export const listMembers = createClientFn("listMembers", "GET") as typeof backendApi.listMembers;
export const updateMemberRole = createClientFn("updateMemberRole", "POST") as typeof backendApi.updateMemberRole;
export const removeMember = createClientFn("removeMember", "POST") as typeof backendApi.removeMember;
export const listInvitations = createClientFn("listInvitations", "GET") as typeof backendApi.listInvitations;
export const createInvitation = createClientFn("createInvitation", "POST") as typeof backendApi.createInvitation;
export const revokeInvitation = createClientFn("revokeInvitation", "POST") as typeof backendApi.revokeInvitation;
export const acceptInvitation = createClientFn("acceptInvitation", "POST") as typeof backendApi.acceptInvitation;
export const lookupInvitation = createClientFn("lookupInvitation", "GET") as typeof backendApi.lookupInvitation;
export const listPermissions = createClientFn("listPermissions", "GET") as typeof backendApi.listPermissions;
export const listRoles = createClientFn("listRoles", "GET") as typeof backendApi.listRoles;
export const createRole = createClientFn("createRole", "POST") as typeof backendApi.createRole;
export const updateRolePermissions = createClientFn("updateRolePermissions", "POST") as typeof backendApi.updateRolePermissions;
export const deleteRole = createClientFn("deleteRole", "POST") as typeof backendApi.deleteRole;
export const listAuditLogs = createClientFn("listAuditLogs", "GET") as typeof backendApi.listAuditLogs;
export const listProjectMembers = createClientFn("listProjectMembers", "GET") as typeof backendApi.listProjectMembers;
export const addProjectMember = createClientFn("addProjectMember", "POST") as typeof backendApi.addProjectMember;
export const listIntegrations = createClientFn("listIntegrations", "GET") as typeof backendApi.listIntegrations;
export const listNotifications = createClientFn("listNotifications", "GET") as typeof backendApi.listNotifications;
export const getMyProfile = createClientFn("getMyProfile", "GET") as typeof backendApi.getMyProfile;
export const updateMyProfile = createClientFn("updateMyProfile", "POST") as typeof backendApi.updateMyProfile;
